### ISSUE TITLE
Which ports should i open

### ISSUE THREAD

**Issue by pratikbin** [krakazyabra/jitsi-helm#2]
First, Amazing work, need little help with TCP ports, i added below ports to my nginx ingress
```yaml
tcp:
 1024: "jitsi/haproxy-0:1024"
 5222: "jitsi/shard-1-prosody:5222"
 5280: "jitsi/shard-1-prosody:5280"
 5347: "jitsi/shard-1-prosody:5347"
```
still getting this `you have been disco...` Help me 
![image](https://user-images.githubusercontent.com/68642400/107851458-226d3500-6e30-11eb-8141-3e3d2dfce036.png)

**Comment by krakazyabra** [comment]
Hi! Did you setup and configured stun/turn server? It is needed for some networks.

**Comment by pratikbin** [comment]
Can you drop link about how to configure/create stunt server, kindly mention ports too i can really utilizes that.

**Comment by krakazyabra** [comment]
F.e. this https://jitsi.github.io/handbook/docs/devops-guide/turn

**Comment by pratikbin** [comment]
ill try it and reopen this if anything needed, thank you
