### ISSUE TITLE
TCP or UDP proxy not configured

### ISSUE THREAD

**Issue by uvwild** [krakazyabra/jitsi-helm#4]
Hello,
I cannot find a place where this is configured.

Am I right in the assumption that you avoided this issue using the nodeports and the kubectl proxy like anyone else?

The proxy for the streams is the real  helm challenge for jitsi.

**Comment by krakazyabra** [comment]
Hello!
Components are using container ports, no nodeports or proxy. 
All incoming transparency traffic goes through haproxy, where rules for jitsi are specified. 

You need to use nodeport only when you're behind NAT (or several NATs), but stun/turn server solves this problem (check https://github.com/krakazyabra/jitsi-helm/issues/2#issuecomment-779773360)

**Comment by uvwild** [comment]
OK.
So do I understand right that your jvb videobridge is not accessible from the outside  world via haproxy and requires TURN to function?
I am banging my head against the tcp/udp proxy wall for a while now. I believe this is important for  high performance jitsi clusters.

**Comment by krakazyabra** [comment]
>videobridge is not accessible from the outside world via haproxy and requires TURN to function

Yes, you're right. When I was preparing this chart, I had no task to make jitsi accessible from outside :)

>this is important for high performance jitsi clusters  

This is about availability of your jitsi instance. All balancing inside is done by haproxy.

**Comment by uvwild** [comment]
I tried istio and nginx so far. 
The tcp/udp proxy is still unsolved. the older examples dont work for  me.
https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/

I will setup my own and near turn server now to get it work and take it from there.
Getting the turn server into the cluster is the helm chart will be the final challenge.

Thanks for the feedback!

**Comment by uvwild** [comment]
Thanks for the feedback.
Seems the TCP UDP connection is a problem....
The nginx example wasn't working for me...
